# Disable random endermite spawning
disable-endermites: true

# Chance to spawn an endermite
endermite-chance: 0.1

# Damage modifiers
pearl-damage-self: 5
pearl-damage-other: 2

# Pearl cooldown in seconds
pearl-cooldown: 0.5

# Sound played when teleporing
pearl-sound: ENDERMAN_TELEPORT

messages:
  no-permission: "&cYou require the permission&e '{permission}'&c to use this command!"
  reloaded: "&aFlamePearls by ArkFlame Development was reloaded!"
  cooldown: "&cWait &e{time}s&c to throw another pearl!"
  stats: |-
    &r 
    &aFlamePearls by ArkFlame Development
    &r 
    &8 » &ePearls Damage: &f{damage}&c♥
    &8 » &ePearls Damage &7(Self)&e: &f{damage-self}&c♥
    &8 » &ePearls Cooldown: &f{cooldown}s
    &r 
    &8 » &ePearls Thrown: &6{thrown}
    &r 