# -------------------------------------------
# FlamePearls General Configuration
# -------------------------------------------

# --- Gameplay Mechanics ---

# Disable the random chance for endermites to spawn from ender pearls.
disable-endermites: true

# If endermites are not disabled, this is the chance (0.0 to 1.0) for one to spawn.
endermite-chance: 0.05

# Prevents players from taking fall damage that was accumulated before they teleported.
reset-fall-damage-after-teleport: true

# Makes a player briefly immune to damage after teleporting (in server ticks, 20 ticks = 1 second).
teleport-no-damage-ticks: 5

# The maximum amount of time a pearl can be alive (in server ticks, 20 ticks = 1 second).
max-ticks-alive: 200

# Prevents players from teleporting to a location outside of the world border.
prevent-world-border-teleport: true

# --- Damage & Cooldowns ---

# Damage dealt to the player who throws the pearl (in half-hearts).
pearl-damage-self: 5.0 # 2.5 hearts

# Damage dealt to other entities hit by the pearl (in half-hearts).
pearl-damage-other: 2.0 # 1 heart

# The default cooldown in seconds for players without a specific permission.
pearl-cooldown: 10.0

# Permission-based cooldowns. Players get the LOWEST value they have permission for.
# The permission node is flamepearls.cooldown.<number>
# It's best practice to keep this list sorted from lowest to highest.
pearl-cooldowns-perms:
  - 1
  - 2
  - 3
  - 5

# --- Cosmetics & World Control ---

# Sound played on a successful pearl teleport.
pearl-sound:
  - "ENDERMAN_TELEPORT"
  - "ENTITY_ENDERMAN_TELEPORT"

# Pearls will behave like vanilla (including glitching) in these worlds.
disabled-worlds:
  - "disabled_world"