name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  flamepearls:
    description: "FlamePearls improves general pearl behaviour and adds new mechanics."
    aliases: [ pearls ]