name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  flamepearls:
    description: "Safe pearl fixer by ArkFlame Development"
    aliases: [ sfp ]